def choose_drawing_set(param: int) -> dict[str, str]:
    DRAWING_SETS = {
        0: {
            "up_left_n_w_corner": "+",
            "up_left_n_corner": "-",
            "up_left_w_corner": "|",
            "up_left_no_corner": " ",
            "up_right_n_e_corner": "+",
            "up_right_n_corner": "-",
            "up_right_e_corner": "|",
            "up_right_no_corner": " ",
            "up_n_e_ne_wall": "---+",
            "up_n_e_wall": "---+",
            "up_n_ne_wall": "----",
            "up_n_wall": "----",
            "up_e_ne_wall": "   +",
            "up_ne_wall": "   -",
            "up_e_wall": "   |",
            "up_no_wall": "    ",
            "cell_left_wall": "|",
            "cell_left_no_wall": " ",
            "cell_right_wall": "   |",
            "cell_w_wall": "   |",
            "cell_no_wall": "    ",
            "cell_closed": "███",
            "cell_path": " ● ",
            "cell_right_closed": "███|",
            "mid_s_ue_de_se_wall": "---+",
            "mid_s_ue_de_wall": "---+",
            "mid_s_ue_se_wall": "---+",
            "mid_s_ue_wall": "---+",
            "mid_s_de_se_wall": "---+",
            "mid_s_de_wall": "---+",
            "mid_s_se_wall": "----",
            "mid_s_wall": "----",
            "mid_ue_de_se_wall": "   +",
            "mid_ue_de_wall": "   |",
            "mid_ue_se_wall": "   +",
            "mid_ue_wall": "   |",
            "mid_de_se_wall": "   +",
            "mid_de_wall": "   |",
            "mid_se_wall": "    ",
            "mid_no_wall": "    ",
            "mid_left_w_sw_s_wall": "+",
            "mid_left_w_sw_wall": "|",
            "mid_left_w_s_wall": "+",
            "mid_left_w_wall": "+",
            "mid_left_sw_s_wall": "+",
            "mid_left_sw_wall": "|",
            "mid_left_s_wall": "-",
            "mid_left_no_wall": " ",
            "mid_right_s_e_se_wall": "---+",
            "mid_right_s_e_wall": "---+",
            "mid_right_s_se_wall": "---+",
            "mid_right_e_se_wall": "   |",
            "mid_right_e_wall": "   |",
            "mid_right_s_wall": "----",
            "mid_right_se_wall": "    ",
            "mid_right_no_wall": "    ",
            "bot_left_w_s_corner": "+",
            "bot_left_w_corner": "+",
            "bot_left_s_corner": "+",
            "bot_left_no_corner": " ",
            "bot_right_e_s_corner": "+",
            "bot_right_e_corner": "+",
            "bot_right_s_corner": "+",
            "bot_right_no_corner": " ",
            "bot_right_wall": "   |",
            "bot_right_closed": "███",
            "bot_right_no_wall": "   ",
            "bot_s_e_es_wall": "---+",
            "bot_s_e_wall": "---+",
            "bot_s_es_wall": "----",
            "bot_s_wall": "----",
            "bot_es_wall": "   -",
            "bot_e_es_wall": "   +",
            "bot_e_wall": "   |",
            "bot_no_wall": "    ",
        },
        1: {
            "up_left_n_w_corner": "┌",
            "up_left_n_corner": "─",
            "up_left_w_corner": "│",
            "up_left_no_corner": " ",
            "up_right_n_e_corner": "┐",
            "up_right_n_corner": "─",
            "up_right_e_corner": "│",
            "up_right_no_corner": " ",
            "up_n_e_ne_wall": "───┬",
            "up_n_e_wall": "───┐",
            "up_n_ne_wall": "────",
            "up_n_wall": "────",
            "up_e_ne_wall": "   ┌",
            "up_ne_wall": "   ╶",
            "up_e_wall": "   │",
            "up_no_wall": "    ",
            "cell_left_wall": "│",
            "cell_left_no_wall": " ",
            "cell_right_wall": "   │",
            "cell_w_wall": "   │",
            "cell_no_wall": "    ",
            "cell_closed": "███",
            "cell_path": " ● ",
            "cell_right_closed": "███│",
            "mid_s_ue_de_se_wall": "───┼",
            "mid_s_ue_de_wall": "───┤",
            "mid_s_ue_se_wall": "───┴",
            "mid_s_ue_wall": "───┘",
            "mid_s_de_se_wall": "───┬",
            "mid_s_de_wall": "───┐",
            "mid_s_se_wall": "────",
            "mid_s_wall": "───╴",
            "mid_ue_de_se_wall": "   ├",
            "mid_ue_de_wall": "   │",
            "mid_ue_se_wall": "   └",
            "mid_ue_wall": "   ╵",
            "mid_de_se_wall": "   ┌",
            "mid_de_wall": "   ╷",
            "mid_se_wall": "   ╶",
            "mid_no_wall": "    ",
            "mid_left_w_sw_s_wall": "├",
            "mid_left_w_sw_wall": "│",
            "mid_left_w_s_wall": "└",
            "mid_left_w_wall": "┘",
            "mid_left_sw_s_wall": "┌",
            "mid_left_sw_wall": "┐",
            "mid_left_s_wall": "╶",
            "mid_left_no_wall": " ",
            "mid_right_s_e_se_wall": "───┤",
            "mid_right_s_e_wall": "───┘",
            "mid_right_s_se_wall": "───┐",
            "mid_right_e_se_wall": "   │",
            "mid_right_e_wall": "   ┘",
            "mid_right_s_wall": "───╴",
            "mid_right_se_wall": "   ┌",
            "mid_right_no_wall": "    ",
            "bot_left_w_s_corner": "└",
            "bot_left_w_corner": "┘",
            "bot_left_s_corner": "┌",
            "bot_left_no_corner": " ",
            "bot_right_e_s_corner": "┘",
            "bot_right_e_corner": "└",
            "bot_right_s_corner": "┐",
            "bot_right_no_corner": " ",
            "bot_right_wall": "   │",
            "bot_right_closed": "███",
            "bot_right_no_wall": "   ",
            "bot_s_e_es_wall": "───┴",
            "bot_s_e_wall": "───┘",
            "bot_s_es_wall": "────",
            "bot_s_wall": "───╴",
            "bot_es_wall": "   ╶",
            "bot_e_es_wall": "   └",
            "bot_e_wall": "   │",
            "bot_no_wall": "    ",
        },
        2: {
            "up_left_n_w_corner": "╔",
            "up_left_n_corner": "═",
            "up_left_w_corner": "║",
            "up_left_no_corner": " ",
            "up_right_n_e_corner": "╗",
            "up_right_n_corner": "═",
            "up_right_e_corner": "║",
            "up_right_no_corner": " ",
            "up_n_e_ne_wall": "═══╦",
            "up_n_e_wall": "═══╗",
            "up_n_ne_wall": "════",
            "up_n_wall": "════",
            "up_e_ne_wall": "   ╔",
            "up_ne_wall": "   ═",
            "up_e_wall": "   ║",
            "up_no_wall": "    ",
            "cell_left_wall": "║",
            "cell_left_no_wall": " ",
            "cell_right_wall": "   ║",
            "cell_w_wall": "   │",
            "cell_no_wall": "    ",
            "cell_closed": "███",
            "cell_path": " ● ",
            "cell_right_closed": "███║",
            "mid_s_ue_de_se_wall": "───┼",
            "mid_s_ue_de_wall": "───┤",
            "mid_s_ue_se_wall": "───┴",
            "mid_s_ue_wall": "───┘",
            "mid_s_de_se_wall": "───┬",
            "mid_s_de_wall": "───┐",
            "mid_s_se_wall": "────",
            "mid_s_wall": "───╴",
            "mid_ue_de_se_wall": "   ├",
            "mid_ue_de_wall": "   │",
            "mid_ue_se_wall": "   └",
            "mid_ue_wall": "   ╵",
            "mid_de_se_wall": "   ┌",
            "mid_de_wall": "   ╷",
            "mid_se_wall": "   ╶",
            "mid_no_wall": "    ",
            "mid_left_w_sw_s_wall": "╠",
            "mid_left_w_sw_wall": "║",
            "mid_left_w_s_wall": "╚",
            "mid_left_w_wall": "╝",
            "mid_left_sw_s_wall": "╔",
            "mid_left_sw_wall": "╗",
            "mid_left_s_wall": "═",
            "mid_left_no_wall": " ",
            "mid_right_s_e_se_wall": "───╣",
            "mid_right_s_e_wall": "───╝",
            "mid_right_s_se_wall": "───╗",
            "mid_right_e_se_wall": "   ║",
            "mid_right_e_wall": "   ╝",
            "mid_right_s_wall": "───╴",
            "mid_right_se_wall": "   ╔",
            "mid_right_no_wall": "    ",
            "bot_left_w_s_corner": "╚",
            "bot_left_w_corner": "╝",
            "bot_left_s_corner": "╔",
            "bot_left_no_corner": " ",
            "bot_right_e_s_corner": "╝",
            "bot_right_e_corner": "╚",
            "bot_right_s_corner": "╗",
            "bot_right_no_corner": " ",
            "bot_right_wall": "   ║",
            "bot_right_closed": "███",
            "bot_right_no_wall": "   ",
            "bot_s_e_es_wall": "═══╩",
            "bot_s_e_wall": "═══╝",
            "bot_s_es_wall": "════",
            "bot_s_wall": "═══╴",
            "bot_es_wall": "   ═",
            "bot_e_es_wall": "   ╚",
            "bot_e_wall": "   ║",
            "bot_no_wall": "    ",
        },
        3: {
            "up_left_n_w_corner": "┏",
            "up_left_n_corner": "━",
            "up_left_w_corner": "┃",
            "up_left_no_corner": " ",
            "up_right_n_e_corner": "┓",
            "up_right_n_corner": "━",
            "up_right_e_corner": "┃",
            "up_right_no_corner": " ",
            "up_n_e_ne_wall": "━━━┳",
            "up_n_e_wall": "━━━┓",
            "up_n_ne_wall": "━━━━",
            "up_n_wall": "━━━┛",
            "up_e_ne_wall": "   ┏",
            "up_ne_wall": "   ━",
            "up_e_wall": "   ┃",
            "up_no_wall": "    ",
            "cell_left_wall": "┃",
            "cell_left_no_wall": " ",
            "cell_right_wall": "   ┃",
            "cell_w_wall": "   ┃",
            "cell_no_wall": "    ",
            "cell_closed": "███",
            "cell_path": " ● ",
            "cell_right_closed": "███┃",
            "mid_s_ue_de_se_wall": "━━━╋",
            "mid_s_ue_de_wall": "━━━┫",
            "mid_s_ue_se_wall": "━━━┻",
            "mid_s_ue_wall": "━━━┛",
            "mid_s_de_se_wall": "━━━┳",
            "mid_s_de_wall": "━━━┓",
            "mid_s_se_wall": "━━━━",
            "mid_s_wall": "━━━━",
            "mid_ue_de_se_wall": "   ┣",
            "mid_ue_de_wall": "   ┃",
            "mid_ue_se_wall": "   ┗",
            "mid_ue_wall": "   ┃",
            "mid_de_se_wall": "   ┏",
            "mid_de_wall": "   ┃",
            "mid_se_wall": "    ",
            "mid_no_wall": "    ",
            "mid_left_w_sw_s_wall": "┣",
            "mid_left_w_sw_wall": "┃",
            "mid_left_w_s_wall": "┗",
            "mid_left_w_wall": "┛",
            "mid_left_sw_wall": "┓",
            "mid_left_s_wall": "━",
            "mid_left_no_wall": " ",
            "mid_left_sw_s_wall": "┏",
            "mid_right_s_e_se_wall": "━━━┫",
            "mid_right_s_e_wall": "━━━┛",
            "mid_right_s_se_wall": "━━━┓",
            "mid_right_e_se_wall": "   ┃",
            "mid_right_e_wall": "   ┗",
            "mid_right_s_wall": "━━━━",
            "mid_right_se_wall": "   ┏",
            "mid_right_no_wall": "    ",
            "bot_left_w_s_corner": "┗",
            "bot_left_w_corner": "┃",
            "bot_left_s_corner": "━",
            "bot_left_no_corner": " ",
            "bot_right_e_s_corner": "┛",
            "bot_right_e_corner": "┗",
            "bot_right_s_corner": "┓",
            "bot_right_no_corner": " ",
            "bot_right_wall": "   ┃",
            "bot_right_closed": "███",
            "bot_right_no_wall": "   ",
            "bot_s_e_es_wall": "━━━┻",
            "bot_s_e_wall": "━━━┛",
            "bot_s_es_wall": "━━━━",
            "bot_s_wall": "━━━┓",
            "bot_es_wall": "   ━",
            "bot_e_es_wall": "   ┗",
            "bot_e_wall": "   ┃",
            "bot_no_wall": "    ",
        }
    }

    def return_size() -> dict[str, str]:
        nonlocal DRAWING_SETS
        return {"size": str(len(DRAWING_SETS.keys()))}

    if param == -1:
        return return_size()

    return DRAWING_SETS.get(param, DRAWING_SETS[3])
