def choose_drawing_set(param: int) -> dict[str, str]:
    DRAWING_SETS = {
        0: {
            "up_left_corner": "+",
            "up_right_corner": "+",
            "up_w_wall": "---+",
            "up_no_wall": "---+",
            "cell_left_wall": "|",
            "cell_right_wall": "   |",
            "cell_w_wall": "   |",
            "cell_no_wall": "    ",
            "cell_closed": "███",
            "cell_path": " ● ",
            "cell_right_closed": "███",
            "mid_s_ue_de_se_wall": "---+",
            "mid_s_ue_de_wall": "---+",
            "mid_s_ue_se_wall": "---+",
            "mid_s_ue_wall": "---+",
            "mid_s_de_se_wall": "---+",
            "mid_s_de_wall": "---+",
            "mid_s_se_wall": "---+",
            "mid_s_wall": "---+",
            "mid_ue_de_se_wall": "   +",
            "mid_ue_de_wall": "   +",
            "mid_ue_se_wall": "   +",
            "mid_ue_wall": "   +",
            "mid_de_se_wall": "   +",
            "mid_de_wall": "   +",
            "mid_se_wall": "   +",
            "mid_no_wall": "    ",
            "mid_left_w_wall": "+",
            "mid_left_no_wall": "+",
            "mid_right_s_wall": "---+",
            "mid_right_no_wall": "   +",
            "bot_left_corner": "+",
            "bot_right_corner": "+",
            "bot_right_wall": "   |",
            "bot_right_closed": "███",
            "bot_right_no_wall": "   ",
            "bot_w_wall": "---+",
            "bot_no_wall": "---+",
        },
        1: {
            "up_left_corner": "┌",
            "up_right_corner": "┐",
            "up_w_wall": "───┬",
            "up_no_wall": "────",
            "cell_left_wall": "│",
            "cell_right_wall": "   │",
            "cell_w_wall": "   │",
            "cell_no_wall": "    ",
            "cell_closed": "███",
            "cell_path": " ● ",
            "cell_right_closed": "███",
            "mid_s_ue_de_se_wall": "───┼",
            "mid_s_ue_de_wall": "───┤",
            "mid_s_ue_se_wall": "───┴",
            "mid_s_ue_wall": "───┘",
            "mid_s_de_se_wall": "───┬",
            "mid_s_de_wall": "───┐",
            "mid_s_se_wall": "────",
            "mid_s_wall": "───╴",
            "mid_ue_de_se_wall": "   ├",
            "mid_ue_de_wall": "   │",
            "mid_ue_se_wall": "   └",
            "mid_ue_wall": "   ╵",
            "mid_de_se_wall": "   ┌",
            "mid_de_wall": "   ╷",
            "mid_se_wall": "   ╶",
            "mid_no_wall": "    ",
            "mid_left_w_wall": "├",
            "mid_left_no_wall": "│",
            "mid_right_s_wall": "───┤",
            "mid_right_no_wall": "   │",
            "bot_left_corner": "└",
            "bot_right_corner": "┘",
            "bot_right_wall": "   │",
            "bot_right_closed": "███",
            "bot_right_no_wall": "   ",
            "bot_w_wall": "───┴",
            "bot_no_wall": "────",
        },
        2: {
            "up_left_corner": "╔",
            "up_right_corner": "╗",
            "up_w_wall": "═══╦",
            "up_no_wall": "════",
            "cell_left_wall": "║",
            "cell_right_wall": "   ║",
            "cell_w_wall": "   │",
            "cell_no_wall": "    ",
            "cell_closed": "███",
            "cell_path": " ● ",
            "cell_right_closed": "███",
            "mid_s_ue_de_se_wall": "───┼",
            "mid_s_ue_de_wall": "───┤",
            "mid_s_ue_se_wall": "───┴",
            "mid_s_ue_wall": "───┘",
            "mid_s_de_se_wall": "───┬",
            "mid_s_de_wall": "───┐",
            "mid_s_se_wall": "────",
            "mid_s_wall": "───╴",
            "mid_ue_de_se_wall": "   ├",
            "mid_ue_de_wall": "   │",
            "mid_ue_se_wall": "   └",
            "mid_ue_wall": "   ╵",
            "mid_de_se_wall": "   ┌",
            "mid_de_wall": "   ╷",
            "mid_se_wall": "   ╶",
            "mid_no_wall": "    ",
            "mid_left_w_wall": "╠",
            "mid_left_no_wall": "║",
            "mid_right_s_wall": "───╣",
            "mid_right_no_wall": "   ║",
            "bot_left_corner": "╚",
            "bot_right_corner": "╝",
            "bot_right_wall": "   ║",
            "bot_right_closed": "███",
            "bot_right_no_wall": "   ",
            "bot_w_wall": "═══╩",
            "bot_no_wall": "════",
        },
        3: {
            "up_left_corner": "┏",
            "up_right_corner": "┓",
            "up_w_wall": "━━━┳",
            "up_no_wall": "━━━━",
            "cell_left_wall": "┃",
            "cell_right_wall": "   ┃",
            "cell_w_wall": "   ┃",
            "cell_no_wall": "    ",
            "cell_closed": "███",
            "cell_path": " ● ",
            "cell_right_closed": "███",
            "mid_s_ue_de_se_wall": "━━━╋",
            "mid_s_ue_de_wall": "━━━┫",
            "mid_s_ue_se_wall": "━━━┻",
            "mid_s_ue_wall": "━━━┛",
            "mid_s_de_se_wall": "━━━┳",
            "mid_s_de_wall": "━━━┓",
            "mid_s_se_wall": "━━━━",
            "mid_s_wall": "━━━━",
            "mid_ue_de_se_wall": "   ┣",
            "mid_ue_de_wall": "   ┃",
            "mid_ue_se_wall": "   ┗",
            "mid_ue_wall": "   ┃",
            "mid_de_se_wall": "   ┏",
            "mid_de_wall": "   ┃",
            "mid_se_wall": "    ",
            "mid_no_wall": "    ",
            "mid_left_w_wall": "┣",
            "mid_left_no_wall": "┃",
            "mid_right_s_wall": "━━━┫",
            "mid_right_no_wall": "   ┃",
            "bot_left_corner": "┗",
            "bot_right_corner": "┛",
            "bot_right_wall": "   ┃",
            "bot_right_closed": "███",
            "bot_right_no_wall": "   ",
            "bot_w_wall": "━━━┻",
            "bot_no_wall": "━━━━",
        }
    }

    def return_size() -> dict[str, str]:
        nonlocal DRAWING_SETS
        return {"size": str(len(DRAWING_SETS.keys()))}

    if param == -1:
        return return_size()

    return DRAWING_SETS.get(param, DRAWING_SETS[3])
